### ISSUE TITLE
Customize Subscription Email subject line

### ISSUE THREAD

**Issue by timler** [rubysherpas/forem#330]
The SubscriptionMailer subject line is currently not customizable.

**Comment by radar** [comment]
Actually, this _is_ customizable. You need to define a translation for `forem.topic.received_reply` within a locale file inside your application, for example `config/locales/en.yml`

``` yml
forem:
  topic:
    received_reply: "You've received a reply!"
```
