### ISSUE TITLE
Translations of ActiveRecord models and attributes

### ISSUE THREAD

**Issue by LegendSzymon-P** [rubysherpas/forem#60]
Models names and attributesm such as Topic and Post, are not translated - for example in a new topic form, i have "Subject" and "Text" instead of translated into in my case Polish.

But even when I add such as translation to my config/locale/pl.yml:

```
pl:
  activerecord:
    attributes:
      topic:
        subject: Temat
        text: Tekst
```

I still have `Subject` and `Text` as labels in new topic form. Why?
